version: '3'

volumes:
  store:
    driver: local
  bundle:
    driver: local

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    links:
      - db
    stdin_open: true
    tty: true
    command: ./bin/rails s
    env_file:
      - ../url-shortener-web.env
  db:
    image: postgres:latest
    ports:
      - 5432:9000
    volumes:
      - store:/var/lib/postgresql/data
    env_file:
      - ../url-shortener-db.env
